# @package _global_
module:
  _target_: emg2qwerty.customs.lightning.ConformerModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  depth: 2
  dim_head: 64
  heads: 8
  ff_mult: 2
  conv_expansion_factor: 2
  conv_kernel_size: 31
  attn_dropout: 0.0
  ff_dropout: 0.0
  conv_dropout: 0.0

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
